using BitigMail.Engine.Planning;using Xunit;
using BitigMail.Engine.Models;using BitigMail.Engine.Storage;
namespace BitigMail.Engine.Tests;
public sealed class Task037PolicyTests
{
 [Fact]public void FolderMappingRejectsTraversalAndCollision(){Assert.Throws<InvalidDataException>(()=>FolderMappingPolicy.Validate([new("a","../x")]));Assert.Throws<InvalidDataException>(()=>FolderMappingPolicy.Validate([new("a","Inbox"),new("b","inbox")]));Assert.NotEmpty(FolderMappingPolicy.Validate([new("a","Müşteri/İş")]).Fingerprint);}
 [Fact]public void PhysicalDuplicatesDefaultPreservedAndMessageIdIsIrrelevant(){var items=new[]{new DuplicateCandidate("p1",new string('a',64),"m"),new DuplicateCandidate("p2",new string('a',64),"m")};Assert.Equal(2,DuplicatePolicyEvaluator.Apply(items,DuplicatePolicy.PreservePhysical).Included.Count);Assert.Single(DuplicatePolicyEvaluator.Apply(items,DuplicatePolicy.ContentOnly).SkippedPhysicalItemIds);}
 [Fact]public void SameBytesDifferentMetadataPolicyIsExplicit(){var items=new[]{new DuplicateCandidate("p1",new string('a',64),"m1"),new DuplicateCandidate("p2",new string('a',64),"m2")};Assert.Equal(2,DuplicatePolicyEvaluator.Apply(items,DuplicatePolicy.ContentAndMetadata).Included.Count);}
 [Fact]public void TemplateRejectsForeignSecretFieldsButAllowsLegitimateSearchWords(){string foreign="{\"Version\":1,\"Root\":{\"Kind\":\"condition\",\"Field\":\"subject\",\"Operator\":\"contains\",\"Text\":\"token\"},\"password\":\"x\"}";Assert.ThrowsAny<Exception>(()=>TransferTemplatePolicy.Serialize(new(1,"token raporu",foreign,[],DuplicatePolicy.PreservePhysical,0)));string json=TransferTemplatePolicy.Serialize(new(1,"token raporu",null,[new("inbox","Inbox")],DuplicatePolicy.PreservePhysical,10));Assert.Contains("token raporu",json);}
 [Fact]public void ArchiveSelectionRejectsChangedMissingAndWrongOwner(){var frozen=ArchiveSearchSelectionPolicy.Freeze("owner","query",[new("id1",new string('a',64))]);ArchiveSearchSelectionPolicy.Revalidate(frozen,"owner",new Dictionary<string,string>{{"id1",new string('a',64)}});Assert.Throws<InvalidDataException>(()=>ArchiveSearchSelectionPolicy.Revalidate(frozen,"other",new Dictionary<string,string>{{"id1",new string('a',64)}}));Assert.Throws<InvalidDataException>(()=>ArchiveSearchSelectionPolicy.Revalidate(frozen,"owner",new Dictionary<string,string>{{"id1",new string('b',64)}}));}
 [Fact]public void MimeAdvancedFilterUsesFullBodyAndFreezesParityFingerprint(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-037-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);try{string eml=Path.Combine(root,"one.eml");File.WriteAllText(eml,"Date: Mon, 01 Jan 2024 00:00:00 +0000\r\nFrom: Alice <alice@example.test>\r\nTo: Bob <bob@example.test>\r\nSubject: Unicode İleti\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n"+new string('x',20000)+" LATE-MARKER");var inspector=new MimeSourceInspector();var manifest=inspector.BuildEmlFilesManifest([eml]);var filter=new MailFilterDefinition(1,new("and",Children:[new("condition","body","contains","late-marker"),new("condition","date","gte",Date:new DateTimeOffset(2024,1,1,0,0,0,TimeSpan.Zero))]));var preflight=new PreflightCheckResult{CanConvert=true};var first=MimeSelectionEngine.EvaluateSelection(manifest,"msrc",null,null,null,preflight,CancellationToken.None,filter);var second=MimeSelectionEngine.EvaluateSelection(manifest,"msrc",null,null,null,preflight,CancellationToken.None,filter);Assert.Equal(1,first.Preview.SelectedMessagesCount);Assert.Equal(0,first.Preview.AdvancedFilterUnknownCount);Assert.Equal(first.Registered.AdvancedFilterFingerprint,second.Registered.AdvancedFilterFingerprint);Assert.Equal(first.Registered.SelectedMessageKeys,second.Registered.SelectedMessageKeys);Assert.NotNull(first.Registered.AdvancedFilterCanonicalJson);}finally{Directory.Delete(root,true);}}
 [Fact]public async Task WaitingPriorityIsStableAndNeverInterruptsActiveJob(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-037-queue-"+Guid.NewGuid().ToString("N"));try{var manager=new BitigMail.LocalHost.Jobs.JobManager(root);var owner=new ClientProjectContext{CompanyId="c",ProjectId="p"};var gate=new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);var order=new List<string>();var active=manager.ScheduleRecovery("active",new string('a',64),owner,async _=>await gate.Task);var low=manager.ScheduleRecovery("low",new string('b',64),owner,_=>{order.Add("low");return Task.CompletedTask;});var high=manager.ScheduleRecovery("high",new string('c',64),owner,_=>{order.Add("high");return Task.CompletedTask;});manager.SetWaitingPriority(low.JobId,1,"c","p");manager.SetWaitingPriority(high.JobId,9,"c","p");Assert.Equal(active.JobId,manager.ActiveRunningJobId);gate.SetResult();for(int i=0;i<100&&order.Count<2;i++)await Task.Delay(20);Assert.Equal(new[]{"high","low"},order);}finally{try{Directory.Delete(root,true);}catch{}}}
}
