using BitigMail.Engine.Storage;
using BitigMail.LocalHost.Security;
using Xunit;

namespace BitigMail.Engine.Tests;
public sealed class Task035SdkAndScaleTests
{
    [Fact] public void MissingLicenseRemainsUnlicensedButSerialWarmupInitializes(){var service=new AsposeSdkStartupService((string?)null);Assert.Equal("unlicensed",service.Status.LicenseState);Assert.Equal("initialized",service.Status.InitializationState);Assert.Equal("LICENSED_OUTPUT_ACCEPTANCE_PENDING",service.Status.Qualification);service.EnsureReady();}
    [Fact] public void InvalidLicenseIsConfigurationErrorAndCannotBeBypassed(){var service=new AsposeSdkStartupService(Path.Combine(Path.GetTempPath(),Guid.NewGuid()+".lic"));Assert.Equal("configuration_error",service.Status.LicenseState);Assert.Throws<InvalidOperationException>(service.EnsureReady);}
    [Fact] public void InvalidLicenseContentIsConfigurationError(){var service=new AsposeSdkStartupService(System.Text.Encoding.UTF8.GetBytes("not-a-license"));Assert.Equal("configuration_error",service.Status.LicenseState);Assert.Throws<InvalidOperationException>(service.EnsureReady);}
    [Fact] public void SelectedLicenseBytesArePersistedProtectedWithoutPathOrPlaintext(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-license-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string selected=Path.Combine(root,"selected.lic");File.WriteAllText(selected,"private-license-material");var store=new AsposeLicenseConfigurationStore(root,new WindowsImapCredentialProtector());store.SaveFromFile(selected);string persisted=Directory.GetFiles(root,"*.protected").Single();Assert.DoesNotContain("private-license-material",File.ReadAllText(persisted),StringComparison.Ordinal);Assert.Equal("private-license-material",System.Text.Encoding.UTF8.GetString(store.Load()!));}
    [Fact] public void OversizedSelectedLicenseIsRejected(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-license-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string selected=Path.Combine(root,"selected.lic");File.WriteAllBytes(selected,new byte[AsposeLicenseConfigurationStore.MaxPlainBytes+1]);var store=new AsposeLicenseConfigurationStore(root,new WindowsImapCredentialProtector());Assert.Throws<InvalidDataException>(()=>store.SaveFromFile(selected));Assert.False(File.Exists(Path.Combine(root,"sdk-license.protected")));}
    [Fact] public void OversizedProtectedConfigurationIsRejected(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-license-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);File.WriteAllBytes(Path.Combine(root,"sdk-license.protected"),new byte[AsposeLicenseConfigurationStore.MaxProtectedBytes+1]);var store=new AsposeLicenseConfigurationStore(root,new WindowsImapCredentialProtector());Assert.Throws<InvalidDataException>(()=>store.Load());}
    [Fact] public async Task ConcurrentSavesPublishOneCompletePayloadWithoutSharedTemp(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-license-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string first=Path.Combine(root,"first.lic"),second=Path.Combine(root,"second.lic");byte[] a=Enumerable.Repeat((byte)'A',65537).ToArray(),b=Enumerable.Repeat((byte)'B',98317).ToArray();File.WriteAllBytes(first,a);File.WriteAllBytes(second,b);var store=new AsposeLicenseConfigurationStore(root,new WindowsImapCredentialProtector());await Task.WhenAll(Task.Run(()=>store.SaveFromFile(first)),Task.Run(()=>store.SaveFromFile(second)));byte[] loaded=store.Load()!;Assert.True(loaded.SequenceEqual(a)||loaded.SequenceEqual(b));Assert.Empty(Directory.GetFiles(root,"*.tmp"));}
    [Fact] public void SmallScaleHarnessPlansCapacityAndRunsIndependentMimeOracle(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-scale-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string eml=Path.Combine(root,"one.eml");File.WriteAllText(eml,"Date: Mon, 1 Jan 2024 00:00:00 +0000\r\nSubject: one\r\n\r\nbody\r\n");var harness=new ScaleAcceptanceHarness();var plan=harness.Plan(root,[eml],new Capacity());Assert.True(plan.CanExecute);Assert.Equal("PLANNED_NOT_EXECUTED",plan.Status);Assert.Equal((1,0,1),harness.SelfCheckEml([eml]));harness.VerifyFixture([(eml,"Inbox")],[new("one.eml","Inbox","2024-01-01T00:00:00.0000000Z","UNKNOWN_NOT_IN_EML",[])]);}
    [Fact] public void ScaleHarnessRejectsCapacityAndDetectsMutation(){string root=Path.Combine(Path.GetTempPath(),"bitigmail-scale-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);string eml=Path.Combine(root,"one.eml");File.WriteAllText(eml,"Subject: one\r\n\r\nbody");var harness=new ScaleAcceptanceHarness();Assert.False(harness.Plan(root,[eml],new NoCapacity()).CanExecute);var plan=harness.Plan(root,[eml],new Capacity());File.AppendAllText(eml,"changed");Assert.Throws<InvalidDataException>(()=>harness.VerifySourcesUnchanged(plan,[eml]));}
    private sealed class Capacity:IDiskCapacityProbe{public DiskCapacityResult Probe(string path)=>new(true,long.MaxValue,null);}
    private sealed class NoCapacity:IDiskCapacityProbe{public DiskCapacityResult Probe(string path)=>new(true,1,null);}
}
