<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BitigMail.OstHarness</RootNamespace>
    <AssemblyName>BitigMail.OstHarness</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Email" Version="24.8.0" />
  </ItemGroup>

</Project>
