import { useEffect, useState } from 'react';
import { localEngineClient } from '../../api/localEngineClient';
import { AppState } from '../../state/useAppState';
import { ConversionReport, FilePickResult, LocalJobRecord, OutlookEmlPreviewResult } from '../../types/localEngine';
import './mimeWorkflow.css';
export function OutlookEmlWorkflow({ state }: { state: AppState }) {
 const company=state.companies.find(c=>c.id===state.plan.companyId)||state.companies[0]; const project=state.projects.find(p=>p.id===state.plan.projectId)||state.projects.find(p=>p.companyId===company?.id); const context={companyId:company?.id||'',companyName:company?.name||'',projectId:project?.id||'',projectName:project?.name||''};
 const [source,setSource]=useState<FilePickResult>(); const [preview,setPreview]=useState<OutlookEmlPreviewResult>(); const [output,setOutput]=useState<FilePickResult>(); const [job,setJob]=useState<LocalJobRecord>(); const [report,setReport]=useState<ConversionReport>(); const [error,setError]=useState('');
 const fidelityLabel=report?.fidelityStatus.includes('DATE_FIDELITY_UNRESOLVED')?'Tarih doğrulaması eksik':'Doğrulama tamamlandı';
 useEffect(()=>{if(!job||!['queued','converting','verifying'].includes(job.status))return;const timer=setInterval(async()=>{try{const next=await localEngineClient.getJob(job.jobId);setJob(next);if(['completed','partially_completed'].includes(next.status))setReport(await localEngineClient.getJobReport(next.jobId));}catch(e){setError(e instanceof Error?e.message:String(e));}},500);return()=>clearInterval(timer)},[job]);
 async function pick(){try{setError('');const s=await localEngineClient.pickOutlookEmlSource();if(s.error)throw new Error(s.error);if(s.handle){setSource(s);setPreview(await localEngineClient.previewOutlookEml(s.handle));}}catch(e){setError(e instanceof Error?e.message:String(e));}}
 async function out(){const o=await localEngineClient.pickOutputDir();if(!o.cancelled)setOutput(o)} async function start(){if(!source?.handle||!output?.handle||!preview)return;try{setJob(await localEngineClient.startOutlookEml({sourceHandle:source.handle,outputDirHandle:output.handle,expectedSourceSha256:preview.sourceSha256,idempotencyKey:crypto.randomUUID(),clientContext:context,enqueueIfBusy:true}))}catch(e){setError(e instanceof Error?e.message:String(e));}}
 return <section className="mime-workflow" data-testid="outlook-eml-workflow"><header className="mime-header"><div><span className="mime-eyebrow">OUTLOOK DOSYALARINDAN</span><h2>PST / OST / OLM → EML klasörleri</h2><p>Sağlıklı posta depolarındaki iletileri yeni ve doğrulanmış EML klasörlerine çıkarır.</p></div></header><div className="mime-context"><span>Müşteri <strong>{context.companyName}</strong></span><span>Proje <strong>{context.projectName}</strong></span></div><div className="mime-notice"><strong>İletiler çıkarılır; bilinen farklar raporda</strong><span>Kaynak değişmez; posta-dışı OLM kayıtları dışarıda sayılır. OLM tarih alanlarında bilinen SDK belirsizliği raporda görünür.</span></div><details><summary>Teknik koruma ayrıntıları</summary><p className="mime-muted">OLM’de tam klasör + Message-ID bire bir eşleşir; özgün ek yükleri ve kaynak XML kanıtı korunur. Whole-message byte-exact iddiası yoktur.</p>{report&&<p className="mime-muted">Teknik durum: {report.fidelityStatus}</p>}</details>{error&&<p className="mime-error" role="alert">{error}</p>}<section className="card mime-card"><h3>1 · Kaynak</h3><button className="btn btn-primary-orange" data-testid="outlook-eml-pick" onClick={pick}>PST, OST veya OLM seç</button><span>{source?.displayPath}</span>{preview&&<p data-testid="outlook-eml-preview"><strong>{preview.sourceFormat.toUpperCase()}</strong> · {preview.qualification}</p>}</section>{preview&&<section className="card mime-card"><h3>2 · Yeni EML çıktısı</h3><button className="btn btn-outline-gray" data-testid="outlook-eml-output" onClick={out}>Çıktı klasörü seç</button><span>{output?.displayPath}</span><button className="btn btn-primary-orange" data-testid="outlook-eml-start" disabled={!output?.handle} onClick={start}>Çıkarımı başlat / sıraya ekle</button>{job&&<p>{job.jobId} · {job.stage}</p>}{report&&<div className="mime-notice" data-testid="outlook-eml-result"><strong>{report.itemsWritten} ileti hazır</strong><span>{fidelityLabel} · {report.reopenedPstVerification.totalAttachmentsVerified} özgün ek doğrulandı</span></div>}</section>}</section>
}
