import React from 'react';
import { localEngineClient } from '../../api/localEngineClient';

type CatalogProject = { projectId: string; name: string };
type CatalogCompany = { companyId: string; name: string; projects?: CatalogProject[] };
type Identity = { userId: string; role: 'Admin' | 'Operator'; companies?: CatalogCompany[] };
type IdentityContextValue = { identity: Identity | null; developmentMode: boolean; setManagementOpen: (open: boolean) => void; logout: () => Promise<void> };
const IdentityContext = React.createContext<IdentityContextValue | null>(null);
export const useIdentity = () => React.useContext(IdentityContext);

export function IdentityGate({ children }: { children: React.ReactNode }) {
  const [mode, setMode] = React.useState<'loading' | 'development' | 'setup' | 'login' | 'ready'>('loading');
  const [userName, setUserName] = React.useState(''); const [password, setPassword] = React.useState('');
  const [error, setError] = React.useState(''); const [notice, setNotice] = React.useState(''); const [submitting, setSubmitting] = React.useState(false);
  const [identity, setIdentity] = React.useState<Identity | null>(null); const [managementOpen, setManagementOpen] = React.useState(false);
  const [company, setCompany] = React.useState(''); const [project, setProject] = React.useState('');
  const [existingCompany, setExistingCompany] = React.useState(''); const [additionalProject, setAdditionalProject] = React.useState('');
  const [newUser, setNewUser] = React.useState(''); const [newPassword, setNewPassword] = React.useState(''); const [newRole, setNewRole] = React.useState<'Admin' | 'Operator'>('Operator');
  const [grantCompany, setGrantCompany] = React.useState(''); const [grantProject, setGrantProject] = React.useState('');

  React.useEffect(() => { localEngineClient.getSetupStatus().then((s) => setMode(s.initialized ? 'login' : 'setup')).catch(() => localEngineClient.initSession().then(() => setMode('development')).catch(() => setError('Yerel motora ulaşılamadı.'))); }, []);
  const refreshIdentity = React.useCallback(async () => { const next = await localEngineClient.getCurrentIdentity(); setIdentity(next); return next as Identity; }, []);
  const logout = async () => { await localEngineClient.logout(); setIdentity(null); setManagementOpen(false); setMode('login'); };
  const requestSetupProof = () => new Promise<string>((resolve, reject) => {
    const bridge = (window as any).chrome?.webview;
    if (!bridge) { const fallback = (window as any).__BITIGMAIL_SETUP_PROOF__; if (fallback) { resolve(fallback); return; } reject(new Error('Güvenli kurulum kanalı kullanılamıyor. BitigMail masaüstü uygulamasını yeniden açın.')); return; }
    let settled = false;
    const finish = (failure?: string, proof?: string) => { if (settled) return; settled = true; clearTimeout(timer); bridge.removeEventListener('message', listener); if (failure) reject(new Error(failure)); else resolve(proof || ''); };
    const listener = (event: any) => { if (event.data?.type === 'bitigmail-setup-proof') finish(undefined, event.data.proof); else if (event.data?.type === 'bitigmail-setup-proof-error') finish(event.data.error || 'Güvenli kurulum kanıtı yenilenemedi.'); };
    const timer = setTimeout(() => finish('Güvenli kurulum kanıtı zamanında alınamadı. BitigMail uygulamasını yeniden açın.'), 10000);
    bridge.addEventListener('message', listener); bridge.postMessage('BITIGMAIL_REFRESH_SETUP');
  });
  const submit = async () => { if (submitting) return; setSubmitting(true); setError(''); try { if (mode === 'setup') { if (password.length < 12) throw new Error('Parola en az 12 karakter olmalıdır.'); const proof = await requestSetupProof(); await localEngineClient.setupFirstAdmin(userName, password, proof); (window as any).__BITIGMAIL_SETUP_PROOF__ = undefined; } else await localEngineClient.login(userName, password); await refreshIdentity(); setMode('ready'); setPassword(''); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Oturum açılamadı.'); } finally { setSubmitting(false); } };
  const createCompany = async () => { setError(''); setNotice(''); try { const created = await localEngineClient.createCatalogCompany(company, project); setGrantCompany(created.companyId); setGrantProject(created.projects?.[0]?.projectId || ''); await refreshIdentity(); setCompany(''); setProject(''); setNotice('Müşteri ve ilk proje oluşturuldu.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Kayıt oluşturulamadı.'); } };
  const createUser = async () => { setError(''); setNotice(''); try { await localEngineClient.createLocalUser(newUser, newPassword, newRole, grantCompany && grantProject ? [{ companyId: grantCompany, projectIds: [grantProject] }] : []); setNewUser(''); setNewPassword(''); setNotice('Kullanıcı oluşturuldu.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Kullanıcı oluşturulamadı.'); } };
  const createProject = async () => { setError(''); setNotice(''); try { await localEngineClient.createCatalogProject(existingCompany, additionalProject); await refreshIdentity(); setAdditionalProject(''); setNotice('Proje oluşturuldu.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Proje oluşturulamadı.'); } };

  if (mode === 'loading') return <main className="identity-shell"><section className="identity-card" aria-live="polite"><img className="identity-logo" src="/bitigmail-mark-v1.png" alt="BitigMail"/><p className="identity-kicker">YEREL POSTA ÇALIŞMA ALANI</p><h1>BitigMail hazırlanıyor</h1>{error ? <><p className="identity-error" role="alert">{error}</p><p className="identity-help">Yerel motoru yeniden başlatın. Sorun sürerse başka bir BitigMail penceresinin açık olmadığını kontrol edin.</p></> : <p className="identity-copy">Güvenli oturum başlatılıyor…</p>}</section></main>;

  if (mode === 'development' || mode === 'ready') return <IdentityContext.Provider value={{ identity, developmentMode: mode === 'development', setManagementOpen, logout }}>
    {children}
    {mode === 'ready' && managementOpen && <div className="modal-backdrop management-backdrop" onMouseDown={(event) => event.currentTarget === event.target && setManagementOpen(false)}><aside className="management-drawer" data-testid="identity-management-drawer" aria-label="Hesap ve çalışma alanı yönetimi">
      <header className="management-header"><div><p className="identity-kicker">BITIGMAIL YÖNETİMİ</p><h2>Hesap ve çalışma alanları</h2><p>{identity?.role === 'Admin' ? 'Yerel yönetici' : 'Yerel operatör'}</p></div><button className="management-close" aria-label="Yönetimi kapat" onClick={() => setManagementOpen(false)}>×</button></header>
      <div className="management-body"><section className="management-section"><div className="management-section-title"><div><h3>Erişebildiğiniz alanlar</h3><p>Posta hesapları yalnızca erişim izniniz olan projelere kaydedilir.</p></div><span className="badge badge-warning">{identity?.companies?.length || 0} müşteri</span></div><div className="catalog-list">{identity?.companies?.length ? identity.companies.map((entry) => <div className="catalog-card" key={entry.companyId}><strong>{entry.name}</strong><span>{entry.projects?.map((item) => item.name).join(' · ') || 'Henüz proje yok'}</span></div>) : <p className="management-empty">Bu hesap için yetkili müşteri veya proje bulunmuyor.</p>}</div></section>
      {identity?.role === 'Admin' && <><section className="management-section"><div className="management-section-title"><div><h3>Yeni çalışma alanı</h3><p>Müşteriyle birlikte ilk projeyi oluşturun.</p></div></div><div className="management-form"><label>Müşteri adı<input value={company} onChange={(e) => setCompany(e.target.value)} placeholder="Örn. Kuzey Lojistik" /></label><label>İlk proje<input value={project} onChange={(e) => setProject(e.target.value)} placeholder="Örn. 2026 posta geçişi" /></label><button className="btn btn-primary-orange" disabled={!company.trim() || !project.trim()} onClick={createCompany}>Çalışma alanı oluştur</button></div></section>
      <section className="management-section"><div className="management-section-title"><div><h3>Mevcut müşteriye proje ekle</h3><p>Yeni posta çalışmalarını ayrı bir proje altında yönetin.</p></div></div><div className="management-form"><label>Müşteri<select aria-label="Proje eklenecek müşteri" value={existingCompany} onChange={(e) => setExistingCompany(e.target.value)}><option value="">Müşteri seçin</option>{identity.companies?.map((item) => <option key={item.companyId} value={item.companyId}>{item.name}</option>)}</select></label><label>Proje adı<input aria-label="Yeni proje adı" value={additionalProject} onChange={(e) => setAdditionalProject(e.target.value)} placeholder="Örn. Arşiv düzenleme" /></label><button className="btn btn-outline-orange" disabled={!existingCompany || !additionalProject.trim()} onClick={createProject}>Projeyi ekle</button></div></section>
      <section className="management-section"><div className="management-section-title"><div><h3>Yeni kullanıcı</h3><p>Rolü ve erişebileceği projeyi açıkça belirleyin.</p></div></div><div className="management-form"><label>Kullanıcı adı<input value={newUser} onChange={(e) => setNewUser(e.target.value)} autoComplete="off" /></label><label>Geçici parola<input type="password" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} autoComplete="new-password" /></label><label>Rol<select aria-label="Rol" value={newRole} onChange={(e) => setNewRole(e.target.value as 'Admin' | 'Operator')}><option value="Operator">Operatör</option><option value="Admin">Yönetici</option></select></label><label>Müşteri<select aria-label="Müşteri" value={grantCompany} onChange={(e) => { setGrantCompany(e.target.value); setGrantProject(identity.companies?.find((item) => item.companyId === e.target.value)?.projects?.[0]?.projectId || ''); }}><option value="">Yetki seçin</option>{identity.companies?.map((item) => <option key={item.companyId} value={item.companyId}>{item.name}</option>)}</select></label><label>Proje<select aria-label="Proje" value={grantProject} onChange={(e) => setGrantProject(e.target.value)}><option value="">Proje seçin</option>{identity.companies?.find((item) => item.companyId === grantCompany)?.projects?.map((item) => <option key={item.projectId} value={item.projectId}>{item.name}</option>)}</select></label><button className="btn btn-primary-orange" disabled={!newUser.trim() || !newPassword || (newRole === 'Operator' && (!grantCompany || !grantProject))} onClick={createUser}>Kullanıcı oluştur</button></div></section></>}
      {error && <p className="identity-error" role="alert">{error}</p>}{notice && <p className="management-notice" role="status">{notice}</p>}<button className="btn btn-outline-gray management-logout" onClick={logout}>Bu cihazda oturumu kapat</button></div>
    </aside></div>}
  </IdentityContext.Provider>;

  return <main className="identity-shell" data-testid="identity-gate"><section className="identity-card"><img className="identity-logo" src="/bitigmail-mark-v1.png" alt="BitigMail"/><p className="identity-kicker">YEREL POSTA ÇALIŞMA ALANI</p><h1>{mode === 'setup' ? 'İlk yönetici kurulumu' : 'BitigMail oturumu'}</h1><p className="identity-copy">{mode === 'setup' ? 'Bu cihaz için ilk yönetici hesabını oluşturun. Verileriniz bu bilgisayarda kalır.' : 'Devam etmek için yerel hesabınızla oturum açın.'}</p><div className="identity-fields"><label>Kullanıcı adı<input className="identity-input" aria-label="Kullanıcı adı" autoComplete="username" value={userName} onChange={(e) => setUserName(e.target.value)} /></label><label>Parola<input className="identity-input" aria-label="Parola" type="password" minLength={mode === 'setup' ? 12 : undefined} autoComplete={mode === 'setup' ? 'new-password' : 'current-password'} value={password} onChange={(e) => setPassword(e.target.value)} />{mode === 'setup' && <small>En az 12 karakter kullanın.</small>}</label></div><button className="btn btn-primary-orange identity-submit" disabled={submitting} onClick={submit}>{submitting ? 'Güvenli kurulum hazırlanıyor…' : mode === 'setup' ? 'Yönetici oluştur' : 'Oturum aç'}</button>{error && <p className="identity-error" role="alert">{error}</p>}<p className="identity-footnote">Bağlantı yalnızca bu cihazdaki güvenli yerel motora yapılır.</p></section></main>;
}
