import {expect,test} from '@playwright/test';
import {spawn} from 'node:child_process';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

test('TASK-039 renders archive governance actions and honest safety notice',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop-reference','One rendered desktop proof is sufficient.');
  const expectedRuntime=path.resolve('..','runtime','testing-engine-secure');if(path.relative(path.resolve('..'),expectedRuntime).split('\\').join('/')!=='runtime/testing-engine-secure')throw new Error('Unexpected test directory');
  const root=path.resolve('..'),runtime=path.join(root,'runtime','testing-engine-secure');fs.rmSync(runtime,{recursive:true,force:true});const proof=crypto.randomBytes(32);const child=spawn(path.join(root,'.tools','dotnet','dotnet.exe'),[path.join(root,'engine','BitigMail.TestingHost','bin','Release','net8.0-windows','BitigMail.TestingHost.dll')],{cwd:root,env:{...process.env,BITIGMAIL_TEST_PRODUCTION_SECURITY:'1'},windowsHide:true,stdio:['pipe','pipe','pipe']});child.stdin.end(proof);
  try{
  await expect.poll(async()=>fetch('http://127.0.0.1:6175/api/setup/status',{headers:{Host:'127.0.0.1:6175'}}).then(r=>r.status).catch(()=>0),{timeout:20_000}).toBe(200);
  await page.addInitScript(value=>{(window as any).__BITIGMAIL_ENGINE_URL__='http://127.0.0.1:6175';(window as any).__BITIGMAIL_SETUP_PROOF__=value;},proof.toString('hex'));
  await page.goto('/');await page.getByLabel('Kullanıcı adı').fill('admin');await page.getByLabel('Parola').fill('correct horse battery');await page.getByRole('button',{name:'Yönetici oluştur'}).click();await expect(page.getByTestId('app-shell')).toBeVisible();
  const base='http://127.0.0.1:6175',origin='http://127.0.0.1:5173';const login=await page.request.post(base+'/api/auth/login',{headers:{Host:'127.0.0.1:6175',Origin:origin,'Content-Type':'application/json'},data:{userName:'admin',password:'correct horse battery'}});const adminToken=(await login.json()).token;const headers={Host:'127.0.0.1:6175',Origin:origin,'Content-Type':'application/json','X-BitigMail-Session':adminToken};
  const sourceCompany=await (await page.request.post(base+'/api/catalog/companies',{headers,data:{name:'Source Company',projectName:'Source Project'}})).json();const destination=await (await page.request.post(base+'/api/catalog/companies',{headers,data:{name:'Empty Destination',projectName:'Restore Target'}})).json();
  await page.request.post(base+'/api/testing/set-mime-source',{headers,data:{fixtureId:'corpus-eml'}});const picked=await (await page.request.post(base+'/api/picker/archive-source',{headers,data:{mode:'eml-files'}})).json();const preview=await (await page.request.post(base+'/api/archive/ingest/preview',{headers,data:{sourceHandle:picked.handle,archiveName:'TASK039 Source Archive',companyId:sourceCompany.companyId,projectId:sourceCompany.projects[0].projectId}})).json();const ingest=await (await page.request.post(base+'/api/archive/ingest/start',{headers,data:{previewId:preview.previewId,idempotencyKey:crypto.randomUUID()}})).json();await expect.poll(async()=>{const r=await page.request.get(base+'/api/jobs/'+ingest.jobId,{headers});return (await r.json()).status;},{timeout:20_000}).toBe('completed');
  await page.getByTestId('nav-tab-search').click();await expect(page.getByText('TASK039 Source Archive',{exact:true})).toBeVisible();await page.getByTestId(`checkbox-archive-${ingest.archiveId}`).check();
  const panel=page.getByTestId('archive-governance-panel');
  await expect(panel).toBeVisible();
  await expect(panel.getByRole('button',{name:'Doğrulanmış yedek oluştur'})).toBeVisible();
  await expect(panel.getByRole('button',{name:'Yedeği yeni arşive geri yükle'})).toBeVisible();
  await expect(panel.getByRole('button',{name:'Saklama önizlemesi'})).toBeVisible();
  await expect(panel.getByRole('button',{name:'Denetim bütünlüğünü kontrol et'})).toBeVisible();
  await expect(panel).toContainText('mevcut arşivler korunur');
  await expect(panel).toContainText('yalnızca önizlemedir');
  const outputResponse=page.waitForResponse(r=>r.url().endsWith('/api/picker/output-dir')&&r.request().method()==='POST');const backupResponse=page.waitForResponse(r=>r.url().endsWith('/api/admin/archive/backup')&&r.request().method()==='POST');await panel.getByRole('button',{name:'Doğrulanmış yedek oluştur'}).click();const outputPick=await (await outputResponse).json();const backup=await (await backupResponse).json();await expect(panel).toContainText('Yedek doğrulandı');const backupPath=path.join(outputPick.displayPath,backup.fileName);expect(fs.existsSync(backupPath)).toBeTruthy();await page.request.post(base+'/api/testing/set-archive-backup',{headers,data:{path:backupPath}});
  await page.getByLabel('Yedek hedef müşterisi').selectOption({label:'Empty Destination'});await page.getByLabel('Yedek hedef projesi').selectOption({label:'Restore Target'});await page.getByLabel('Saklama yaşı gün').fill('30');await panel.getByRole('button',{name:'Saklama önizlemesi'}).click();await expect(panel).toContainText('hiçbir arşiv silinmedi');
  const restorePickerResponse=page.waitForResponse(r=>r.url().endsWith('/api/picker/archive-backup')&&r.request().method()==='POST');const restoreResponse=page.waitForResponse(r=>r.url().endsWith('/api/admin/archive/restore')&&r.request().method()==='POST');await panel.getByRole('button',{name:'Yedeği yeni arşive geri yükle'}).click();expect((await restorePickerResponse).status()).toBe(200);const restoredHttp=await restoreResponse;expect(restoredHttp.status(),await restoredHttp.text()).toBe(200);await expect(panel).toContainText('Geri yükleme tamamlandı: 12 ileti',{timeout:20_000});const restoredCatalog=await (await page.request.get(base+'/api/archive/catalog',{headers})).json();expect(restoredCatalog.filter((x:any)=>x.companyId===destination.companyId&&x.projectId===destination.projects[0].projectId&&x.totalItems===12)).toHaveLength(1);
  await page.request.post(base+'/api/admin/users',{headers,data:{userName:'operator039',password:'operator secure password',role:'Operator',grants:[{companyId:sourceCompany.companyId,projectIds:[sourceCompany.projects[0].projectId]}]}});const operatorToken=(await (await page.request.post(base+'/api/auth/login',{headers:{Host:'127.0.0.1:6175',Origin:origin,'Content-Type':'application/json'},data:{userName:'operator039',password:'operator secure password'}})).json()).token;const operatorHeaders={...headers,'X-BitigMail-Session':operatorToken};const operatorOutput=await (await page.request.post(base+'/api/picker/output-dir',{headers:operatorHeaders,data:{}})).json();const operatorSource=await (await page.request.post(base+'/api/picker/archive-backup',{headers:operatorHeaders,data:{}})).json();
  expect((await page.request.post(base+'/api/admin/archive/backup',{headers:operatorHeaders,data:{scopes:[{companyId:sourceCompany.companyId,projectId:sourceCompany.projects[0].projectId,archiveId:ingest.archiveId}],outputDirectoryHandle:operatorOutput.handle}})).status()).toBe(404);expect((await page.request.post(base+'/api/admin/archive/restore',{headers:operatorHeaders,data:{sourceHandle:operatorSource.handle,companyId:destination.companyId,projectId:destination.projects[0].projectId}})).status()).toBe(404);expect((await page.request.post(base+'/api/admin/archive/retention-preview',{headers:operatorHeaders,data:{companyId:destination.companyId,projectId:destination.projects[0].projectId,olderThanDays:30}})).status()).toBe(404);expect((await page.request.get(base+'/api/admin/audit',{headers:operatorHeaders})).status()).toBe(404);expect((await page.request.get(base+'/api/admin/jobs/'+ingest.jobId+'/delivery-report',{headers:operatorHeaders})).status()).toBe(404);
  }finally{if(child.exitCode===null){const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;}}
});
