using System;
using System.Collections.Generic;

namespace BitigMail.Engine.Imap.Transfer;

/// <summary>
/// Lifecycle states for an individual transfer item in the durable journal.
/// </summary>
public enum ImapTransferItemStatus
{
    Planned,
    AppendIntent,
    Verified,
    NeedsAttention,
    Failed
}

/// <summary>
/// Frozen metadata for a single item within an immutable transfer plan.
/// </summary>
public sealed class ImapTransferPlannedItem
{
    public required string ItemId { get; set; }
    public required string SourceFolder { get; set; }
    public required string SourceDelimiter { get; set; }
    public required uint SourceUid { get; set; }
    public required uint SourceUidValidity { get; set; }
    public required string SourceSha256 { get; set; }
    public DateTimeOffset? OriginalMimeDateUtc { get; set; }
    public DateTimeOffset InternalDateUtc { get; set; }
    public List<string> Flags { get; set; } = new();
    public List<string> Keywords { get; set; } = new();
    public required string TargetFolder { get; set; }
}

/// <summary>
/// Dedicated immutable transfer plan generated by preview and stored durably on disk.
/// Contains all frozen data needed to execute and verify the transfer.
/// </summary>
public sealed class ImapTransferPlan
{
    public string? AdvancedFilterCanonicalJson { get; set; }
    public string? AdvancedFilterFingerprint { get; set; }
    public int AdvancedFilterUnknownCount { get; set; }
    public string? CompanyName { get; set; }
    public string? ProjectName { get; set; }
    public string? SourceDisplayName { get; set; }
    public string? TargetDisplayName { get; set; }
    public required string PlanId { get; set; }
    public required string PreviewId { get; set; }
    public required string CompanyId { get; set; }
    public required string ProjectId { get; set; }
    public required string SourceAccountId { get; set; }
    public required long SourceAccountVersion { get; set; }
    public required string TargetAccountId { get; set; }
    public required long TargetAccountVersion { get; set; }
    public List<ImapTransferPlannedItem> Items { get; set; } = new();
    public DateTimeOffset CreatedAtUtc { get; set; } = DateTimeOffset.UtcNow;
    public bool CanTransfer { get; set; }
    public ImapTransferPreviewResponse? Preview { get; set; }
    public string? StartDate { get; set; }
    public string? EndDate { get; set; }
    public string? BlockerReason { get; set; }
}

/// <summary>
/// Folder path equality comparer implementing RFC 3501 case-insensitivity for INBOX
/// while enforcing strict case-sensitivity for all other folder names.
/// </summary>
public sealed class ImapFolderPathComparer : IEqualityComparer<string>
{
    public static readonly ImapFolderPathComparer Instance = new();

    public bool Equals(string? x, string? y)
    {
        if (ReferenceEquals(x, y)) return true;
        if (x is null || y is null) return false;
        if (string.Equals(x, "INBOX", StringComparison.OrdinalIgnoreCase) &&
            string.Equals(y, "INBOX", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }
        return string.Equals(x, y, StringComparison.Ordinal);
    }

    public int GetHashCode(string obj)
    {
        if (string.Equals(obj, "INBOX", StringComparison.OrdinalIgnoreCase))
        {
            return StringComparer.OrdinalIgnoreCase.GetHashCode("INBOX");
        }
        return StringComparer.Ordinal.GetHashCode(obj);
    }
}

/// <summary>
/// Durable per-item record in the transfer journal.
/// </summary>
public sealed class ImapTransferJournalEntry
{
    public required string ItemId { get; set; }
    public ImapTransferItemStatus Status { get; set; } = ImapTransferItemStatus.Planned;
    public string? BitigMailKeyword { get; set; }
    public required string SourceFolder { get; set; }
    public required uint SourceUid { get; set; }
    public required uint SourceUidValidity { get; set; }
    public required string TargetFolder { get; set; }
    public uint? TargetUidValidity { get; set; }
    public uint? TargetUid { get; set; }
    public required string ExpectedSha256 { get; set; }
    public string? VerifiedSha256 { get; set; }
    public DateTimeOffset? TargetInternalDateUtc { get; set; }
    public List<string>? TargetFlags { get; set; }
    public string? ErrorMessage { get; set; }
    public DateTimeOffset UpdatedAtUtc { get; set; } = DateTimeOffset.UtcNow;
}

/// <summary>
/// Complete durable journal state for a transfer job.
/// </summary>
public sealed class ImapTransferJournalState
{
    public required string JobId { get; set; }
    public required string PlanId { get; set; }
    public Dictionary<string, ImapTransferJournalEntry> Entries { get; set; } = new(StringComparer.Ordinal);
    public DateTimeOffset UpdatedAtUtc { get; set; } = DateTimeOffset.UtcNow;
}
